### ISSUE TITLE
Reporting a Login Bug Message

### ISSUE THREAD

**Issue by splinks** [Klauensprung/AviDrugZ#1]
This message is coming up after trying to sign in on the app running it in either admin or normal 
![image](https://user-images.githubusercontent.com/35834750/219947855-69adefc7-23ef-4d83-a6f2-6a6f94b539d1.png)

**Comment by ROBdk97** [comment]
The app currently only supports email 2fa

**Comment by Klauensprung** [comment]
Thanks for your feedback, I added the functionality to use authenticator codes in 
2ea33ce65def3ead0600457d164a5e533bac674c
